### ISSUE TITLE
Should we pass `-stdlib=libc++` when building with `clang`?

### ISSUE THREAD

**Issue by MarijnS95** [cloudpeers/xbuild#75]
Currently running into this on a custom CI image when building for Android: https://stackoverflow.com/questions/26333823/clang-doesnt-see-basic-headers

Seems the default is `-stdlib=libstdc++` which comes from `gcc-c++`, but our build should use the headers from `"--sysroot=$HOME/.cache/x/Android.ndk"`. The build starts working when using `-stdlib=libc++` which I think makes sense to add, since we "only do pure `clang` builds" anyway? Sorry, not very familiar with all the C/C++ header magic :sweat_smile:

EDIT: Made this change on my fork to be unblocked by this error: https://github.com/MarijnS95/xbuild/commit/bcc952494e6890c1fbbdf42584583b40106bcc4b

**Comment by dvc94ch** [comment]
seems like a reasonable change to make. I guess this should change on all platforms?
